### ISSUE TITLE
Allow flexibility to have varied axis ordering in  the dataset.

### ISSUE THREAD

**Issue by lmanan** [funkelab/funlib.show.neuroglancer#6]
In the code currently, we parse the array to find the number of spatial and channel dims [here](https://github.com/funkelab/funlib.show.neuroglancer/blob/ee52c8de63dce138c4569ac0e07925bf4255acd0/funlib/show/neuroglancer/add_layer.py#L40) and then initialize a neuroglancer coordinate space [here](https://github.com/funkelab/funlib.show.neuroglancer/blob/ee52c8de63dce138c4569ac0e07925bf4255acd0/funlib/show/neuroglancer/add_layer.py#L74). 

If the dataset were defined with an axes ordering such as (`t`, `c`, `z`, `y`, `x`), then currently we would treat time (`t`) as the channel (`c`) dimension because of the prepending of the channel dim to the spatial (spatio-temporal) dims [here](https://github.com/funkelab/funlib.show.neuroglancer/blob/ee52c8de63dce138c4569ac0e07925bf4255acd0/funlib/show/neuroglancer/add_layer.py#L66).

Maybe, if provided,  the `.zattrs` file should be read to figure out the correct axis ordering and then the  neuroglancer coordinate space could be initialized appropriately.

**Comment by pattonw** [comment]
now supported since this was added to `funlib.persistence`
